services:
  app:
    container_name: salt-lite-php
    build:
      context: ./
      dockerfile: Dockerfile
      target: development-php
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    platform: linux/amd64
    volumes:
      - ${SOURCE_DIR:-./}:/app
    env_file:
      - .env
    environment:
      PHP_IDE_CONFIG: "serverName=cli" # Used by PhpStorm for path mapping
      COMPOSER_AUTH: '{"github-oauth": {"github.com":"${GITHUB_TOKEN}"}}'
    extra_hosts:
      - host.docker.internal:host-gateway
